apiVersion: apps/v1 
kind: Deployment
metadata:
  name: app1
  # these are replica set labels
  labels:
    purpose: ingress-demo
    project: roboshop
    app: app1 
spec: 
  replicas: 2
  selector:
  # these are used to select pods
    matchLabels:
      purpose: dp-demo
      project: roboshop
      app: app1
  # pod definition
  template:
    metadata:
      labels:
        purpose: ingress-demo
        project: roboshop
        app: app1
    spec:
      containers:
      - name: app1
        image: suryamalli/app1:v1
---
apiVersion: v1 
kind: Service 
metadata:
  name: app1 
spec:
  selector:
    purpose: ingress-demo
    project: roboshop
    app: app1
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80